-- Archemy Database Schema
-- Reconstructed from ADF Entity Object definitions

CREATE DATABASE IF NOT EXISTS archemy;
USE archemy;

-- Table: domains
CREATE TABLE IF NOT EXISTS domains (
  DOMAIN_ID INT NOT NULL AUTO_INCREMENT,
  DOMAIN_NAME VARCHAR(45) NOT NULL,
  DOMAIN_DESCRIPTION VARCHAR(45),
  PRIMARY KEY (DOMAIN_ID)
);

-- Table: recurring_bus_problem
CREATE TABLE IF NOT EXISTS recurring_bus_problem (
  ID INT NOT NULL AUTO_INCREMENT,
  BUSINESS_PROBLEM VARCHAR(500) NOT NULL,
  CONTEXT VARCHAR(80),
  DESCRIPTION VARCHAR(500),
  TYPE VARCHAR(80),
  PRIMARY KEY (ID)
);

-- Table: kads
CREATE TABLE IF NOT EXISTS kads (
  KAD_ID INT NOT NULL AUTO_INCREMENT,
  KAD_NAME VARCHAR(100),
  DOMAIN_ID INT,
  KAD_LINK VARCHAR(300),
  KAD_LINK_PUBLIC VARCHAR(300),
  KAD_HIT_COUNTER INT,
  RECURRING_BUS_PROBLEM_ID INT NOT NULL,
  PRIMARY KEY (KAD_ID),
  CONSTRAINT KAD_DOMAIN_ID_FK FOREIGN KEY (DOMAIN_ID) REFERENCES domains (DOMAIN_ID)
);

-- Table: dimensions
CREATE TABLE IF NOT EXISTS dimensions (
  DIMENSION_ID INT NOT NULL AUTO_INCREMENT,
  DIMENSION_NAME VARCHAR(45),
  DOMAIN_ID INT NOT NULL,
  PRIMARY KEY (DIMENSION_ID),
  CONSTRAINT DIMENSION_DOMAIN_ID_FK FOREIGN KEY (DOMAIN_ID) REFERENCES domains (DOMAIN_ID)
);

-- Table: areas
CREATE TABLE IF NOT EXISTS areas (
  AREA_ID INT NOT NULL AUTO_INCREMENT,
  AREA_PARENT_ID INT,
  AREA_ORDER_NO VARCHAR(45),
  AREA_DEPTH_LEVEL INT,
  DIMENSION_ID INT,
  AREA_NAME VARCHAR(100),
  PRIMARY KEY (AREA_ID),
  CONSTRAINT AREA_DIMENSION_ID_FK FOREIGN KEY (DIMENSION_ID) REFERENCES dimensions (DIMENSION_ID),
  CONSTRAINT FK_AREAS_EO FOREIGN KEY (AREA_PARENT_ID) REFERENCES areas (AREA_ID)
);

-- Table: kad_dimensions_area
CREATE TABLE IF NOT EXISTS kad_dimensions_area (
  ID INT NOT NULL AUTO_INCREMENT,
  DIMENSION_ID INT NOT NULL,
  KAD_ID INT NOT NULL,
  AREA_ID INT NOT NULL,
  AREA_PARENT_ID INT,
  PRIMARY KEY (ID),
  CONSTRAINT KAD_DIM_KAD_ID_FK FOREIGN KEY (KAD_ID) REFERENCES kads (KAD_ID) ON DELETE CASCADE,
  CONSTRAINT KAD_DIM_ID_FK FOREIGN KEY (DIMENSION_ID) REFERENCES dimensions (DIMENSION_ID) ON DELETE CASCADE,
  CONSTRAINT KAD_DIM_AREA FOREIGN KEY (AREA_ID) REFERENCES areas (AREA_ID) ON DELETE CASCADE
);

-- Table: iads
CREATE TABLE IF NOT EXISTS iads (
  IAD_ID INT NOT NULL AUTO_INCREMENT,
  IAD_NAME VARCHAR(100),
  IAD_TYPE VARCHAR(100) NOT NULL,
  DOMAIN_ID INT,
  KAD_ID INT,
  PRIMARY KEY (IAD_ID),
  CONSTRAINT IAD_DOMAIN_ID_FK FOREIGN KEY (DOMAIN_ID) REFERENCES domains (DOMAIN_ID),
  CONSTRAINT IAD_KAD_ID_FK FOREIGN KEY (KAD_ID) REFERENCES kads (KAD_ID)
);

-- Table: customer_info
CREATE TABLE IF NOT EXISTS customer_info (
  USER_ID VARCHAR(150) NOT NULL,
  CUSTOMER_NAME VARCHAR(150),
  INDUSTRY VARCHAR(150),
  PRIMARY KEY (USER_ID)
);
