ldap.server.type=apacheds
ldap.host=apacheds
ldap.port=10389
root.dn=uid=admin,ou=system
cfg.root.pw=secret
ldap.client.type=apache
suffix.name=example
suffix.dc=com
suffix=dc=example,dc=com
users.dn=ou=People,dc=example,dc=com
roles.dn=ou=Roles,ou=RBAC,dc=example,dc=com
policies.dn=ou=Policies,dc=example,dc=com
perms.dn=ou=Permissions,ou=RBAC,dc=example,dc=com
constraints.dn=ou=Constraints,ou=RBAC,dc=example,dc=com
userous.dn=ou=OS-U,ou=ARBAC,dc=example,dc=com
permous.dn=ou=OS-P,ou=ARBAC,dc=example,dc=com
adminroles.dn=ou=AdminRoles,ou=ARBAC,dc=example,dc=com
adminperms.dn=ou=AdminPerms,ou=ARBAC,dc=example,dc=com
groups.dn=ou=Groups,dc=example,dc=com
admin.min.conn=1
admin.max.conn=10
user.min.conn=1
user.max.conn=10
min.log.conn=1
max.log.conn=3
group.objectclass=configGroup
group.protocol=configProtocol
group.properties=configParameter
rfc2307=false
